apiVersion: v1
kind: ReplicationController
metadata:
  name: RC_name
  labels:
    env: production
spec:
  replicas: 3             #number of pods
  selector:               #not required
    app: myapp         
  template:               #define the pod which will be used by RC to create new replicas
    metadata:
      name: pod_name
      labels:
        app: myapp
    spec:
      containers:
        - name: container_name
          image: image_name