apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-backup
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-backup
    spec:
      containers:
      - name: backup-container
        image: your-backup-image:tag
        command: ["backup-script.sh"] # Replace with the actual backup command or script
      restartPolicy: OnFailure   # or Never